"""db setup

Revision ID: 49594fb86f85
Revises: 
Create Date: 2022-01-01 01:06:12.498321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '6197cc2d4e58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('country_name', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('total_cases', mysql.INTEGER(display_width=255), autoincrement=False, nullable=False),
    sa.Column('new_cases', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.Column('total_deaths', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.Column('new_deaths', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.Column('total_recovered', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.Column('new_recovered', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.Column('active_cases', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.Column('serious_cases', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.Column('total_cases_per_m', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.Column('deaths_per_m', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.Column('total_tests', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.Column('tests_per_m', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.Column('population', mysql.INTEGER(display_width=255), autoincrement=False, nullable=True),
    sa.Column('new_cases_per_m', mysql.FLOAT(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
